---
title: "CMCSA"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
require(xts)
require(qrmdata)
require(quantreg)
require(quantmod)
require(matrixStats)

tickers <- c("CMCSA")
getSymbols(tickers)
cmcsa_price <- as.zoo(CMCSA[,6])
cmcsa_return <- diff(log(cmcsa_price))[-1]*100

plot((cmcsa_return))
boxplot(as.vector(cmcsa_return), title = "CMCSA", main = "CMCSA Daily % Change", col = "blue", cex = 0.5, pch = 19)
```

COMCAST
==============================================

Column {data-width=650}
-----------------------------------------------------------------------

### MAIN

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### DAILY RETURNS

```{r}
plot((cmcsa_return), title = "CMCSA", main = "CMCSA Returns over time")
```

### DAILY PERCENT CHANGE

```{r}
boxplot(as.vector(cmcsa_return), title = "CMCSA", main = "CMCSA Daily % Change", col = "blue", cex = 0.5, pch = 19)
```

ALL
==============================================

```{r echo=FALSE, message=FALSE, warning=FALSE}
## +++++++++++++++++++++++++++++++++++++++++++++++++++++
## ALL COMPANIES
## +++++++++++++++++++++++++++++++++++++++++++++++++++++

## 1: GET THE DATA
## -- Add stock tickers
## -- use quantmod getSymbols

tickers <- c("CMCSA", "DIS", "DISH", "NFLX")
getSymbols(tickers)

## 2: CALCULATE RETURNS
## -- get the returns (_r) for each using the closing (not adjusted?) amount 
## -- remove/clean up missing values (na.omit)

CMCSA_r <- na.omit(diff(log(CMCSA[,4]))[-1])
DIS_r <- na.omit(diff(log(DIS[,4]))[-1])
DISH_r <- na.omit(diff(log(DISH[,4]))[-1])
NFLX_r <- na.omit(diff(log(NFLX[,4]))[-1])

```

### All Returns

```{r}
## 3. PUT IT ALL TOGETHER
ALL_r <- na.omit(merge(CMCSA_r, DIS_r, DISH_r, NFLX_r))
plot(ALL_r)
```

### ACF

```{r}
## 4. AUTOCORRELATIONS
par(mfrow = c(2,1))
acf(ALL_r)
```

### ABS ACF

```{r}
## 4. AUTOCORRELATIONS
par(mfrow = c(2,1))
acf(abs(ALL_r))
```

### PACF

```{r}
## 4. PARTIAL AUTOCORRELATIONS
par(mfrow = c(2,1))
pacf(ALL_r)
```
### ABS PACF

```{r}
## 4. PARTIAL AUTOCORRELATIONS
par(mfrow = c(2,1))
pacf(abs(ALL_r))
```

### CORRELATIONS

```{r}
## 5. CORRELATIONS
## Using matrixstats
ALL_corr <- apply.monthly(ALL_r, FUN = cor)
plot(ALL_corr)
```

### VOLATILITY

```{r}
## 6. VOLATILITY
## Using matrixstats
ALL_vols <- apply.monthly(ALL_r, FUN = colSds)
plot(ALL_vols)
```


FIN.